services:
  fishing_bot:
    build: .
    environment:
      # These values are only recognized when no config file exists / is persisted!
      # These are the default values.
      MC_SERVER: 127.0.0.1
      # MC_PORT: 25565
      # MC_ONLINE_MODE: "true"
      # MC_PROTOCOL: AUTOMATIC
    volumes:
      # to persist and edit the config file and the refreshToken, uncomment the line below
      # - ./afkbot-data:/usr/lib/afkbot/data
      - logs:/var/log/afkbot/
volumes:
  logs:
